export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './authController.serviceInterface';
export * from './categoriaIngrediente.service';
import { CategoriaIngredienteService } from './categoriaIngrediente.service';
export * from './categoriaIngrediente.serviceInterface';
export * from './ingrediente.service';
import { IngredienteService } from './ingrediente.service';
export * from './ingrediente.serviceInterface';
export * from './listaCompraResource.service';
import { ListaCompraResourceService } from './listaCompraResource.service';
export * from './listaCompraResource.serviceInterface';
export * from './menuSemanal.service';
import { MenuSemanalService } from './menuSemanal.service';
export * from './menuSemanal.serviceInterface';
export * from './receta.service';
import { RecetaService } from './receta.service';
export * from './receta.serviceInterface';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export * from './usuarios.serviceInterface';
export const APIS = [AuthControllerService, CategoriaIngredienteService, IngredienteService, ListaCompraResourceService, MenuSemanalService, RecetaService, UsuariosService];
