/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiRespuestaBoolean } from '../model/models';
import { ApiRespuestaListIngredienteDto } from '../model/models';
import { IngredienteDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface IngredienteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param ingredienteDto 
     */
    actualizarIngrediente(ingredienteDto: IngredienteDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * 
     * 
     * @param ingredienteDto 
     */
    altaIngrediente(ingredienteDto: IngredienteDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * 
     * 
     * @param ingredienteDto 
     */
    eliminarIngrediente(ingredienteDto: IngredienteDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * 
     * 
     * @param categoria 
     */
    obtenerIngredientePorCategoria(categoria: string, extraHttpRequestParams?: any): Observable<ApiRespuestaListIngredienteDto>;

    /**
     * 
     * 
     */
    obtenerTodosIngredientes(extraHttpRequestParams?: any): Observable<ApiRespuestaListIngredienteDto>;

}
