/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiRespuestaListListaCompraDto } from '../model/models';
import { ApiRespuestaListaCompraDto } from '../model/models';
import { ApiRespuestaVoid } from '../model/models';
import { EliminarListaDto } from '../model/models';
import { GenerarListaDto } from '../model/models';
import { ModificarItemsDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ListaCompraResourceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param modificarItemsDto 
     */
    anadirItems(modificarItemsDto: ModificarItemsDto, extraHttpRequestParams?: any): Observable<ApiRespuestaListaCompraDto>;

    /**
     * 
     * 
     * @param eliminarListaDto 
     */
    eliminarLista(eliminarListaDto: EliminarListaDto, extraHttpRequestParams?: any): Observable<ApiRespuestaVoid>;

    /**
     * 
     * 
     * @param generarListaDto 
     */
    generarLista(generarListaDto: GenerarListaDto, extraHttpRequestParams?: any): Observable<ApiRespuestaListaCompraDto>;

    /**
     * 
     * 
     */
    obtenerMisListas(extraHttpRequestParams?: any): Observable<ApiRespuestaListListaCompraDto>;

    /**
     * 
     * 
     * @param modificarItemsDto 
     */
    quitarItems(modificarItemsDto: ModificarItemsDto, extraHttpRequestParams?: any): Observable<ApiRespuestaListaCompraDto>;

}
