/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActualizarRecetasMenuDto } from '../model/models';
import { AddRecetaDto } from '../model/models';
import { ApiRespuestaBoolean } from '../model/models';
import { ApiRespuestaListMenuSemanalDto } from '../model/models';
import { ApiRespuestaMenuSemanalDto } from '../model/models';
import { MenuSemanalCreateDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MenuSemanalServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param actualizarRecetasMenuDto 
     */
    actualizarRecetasMenu(actualizarRecetasMenuDto: ActualizarRecetasMenuDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param addRecetaDto 
     */
    addReceta(addRecetaDto: AddRecetaDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * 
     * 
     * @param menuSemanalCreateDto 
     */
    crearMenuSemanal(menuSemanalCreateDto: MenuSemanalCreateDto, extraHttpRequestParams?: any): Observable<ApiRespuestaMenuSemanalDto>;

    /**
     * 
     * 
     * @param menuId 
     */
    eliminarMenu(menuId: number, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     */
    obtenerMenu(id: number, extraHttpRequestParams?: any): Observable<ApiRespuestaMenuSemanalDto>;

    /**
     * 
     * 
     */
    obtenerMisMenus(extraHttpRequestParams?: any): Observable<ApiRespuestaListMenuSemanalDto>;

}
