/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ActualizarUsuarioDto } from '../model/models';
import { ApiRespuestaBoolean } from '../model/models';
import { ApiRespuestaUsuarioDto } from '../model/models';
import { UsuarioDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsuariosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param actualizarUsuarioDto 
     */
    actualizarUsuario(actualizarUsuarioDto: ActualizarUsuarioDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * 
     * 
     * @param usuarioDto 
     */
    altaUsuario(usuarioDto: UsuarioDto, extraHttpRequestParams?: any): Observable<ApiRespuestaBoolean>;

    /**
     * 
     * 
     */
    obtenerUsuarioPorEmail(extraHttpRequestParams?: any): Observable<ApiRespuestaUsuarioDto>;

}
