/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiaComidaDto } from './diaComidaDto';


export interface ActualizarRecetasMenuDto { 
    menuId?: number;
    diasComidas?: Array<DiaComidaDto>;
}

