/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarUsuarioDto { 
    username?: string;
    nombre?: string;
    apellido?: string;
    email?: string;
    passwordAntiguo?: string;
    passwordNuevo?: string;
}

