/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IngredienteDto } from './ingredienteDto';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaListIngredienteDto { 
    data?: Array<IngredienteDto>;
    estado?: ApiRespuestaListIngredienteDto.EstadoEnum;
}
export namespace ApiRespuestaListIngredienteDto {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


