/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecetaDto } from './recetaDto';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaListRecetaDto { 
    data?: Array<RecetaDto>;
    estado?: ApiRespuestaListRecetaDto.EstadoEnum;
}
export namespace ApiRespuestaListRecetaDto {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


