/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaVoid { 
    data?: object;
    estado?: ApiRespuestaVoid.EstadoEnum;
}
export namespace ApiRespuestaVoid {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


