/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoginResponse } from './loginResponse';


/**
 * Respuestas estandarizadas de la api
 */
export interface ApiRespuestaLoginResponse { 
    data?: LoginResponse;
    estado?: ApiRespuestaLoginResponse.EstadoEnum;
}
export namespace ApiRespuestaLoginResponse {
    export type EstadoEnum = 'exito' | 'error';
    export const EstadoEnum = {
        Exito: 'exito' as EstadoEnum,
        Error: 'error' as EstadoEnum
    };
}


