/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IngredienteSimpleDto } from './ingredienteSimpleDto';


export interface ListaCompraDto { 
    id?: number;
    usuarioId?: number;
    items?: Array<IngredienteSimpleDto>;
}

