/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListaCompraDto } from './listaCompraDto';
import { MenuSemanalDto } from './menuSemanalDto';


export interface UsuarioDto { 
    id?: number;
    username?: string;
    password?: string;
    nombre?: string;
    apellido?: string;
    email?: string;
    rol?: UsuarioDto.RolEnum;
    fechaCreacion?: string;
    listaCompras?: Array<ListaCompraDto>;
    menuSemanal?: Array<MenuSemanalDto>;
}
export namespace UsuarioDto {
    export type RolEnum = 'ADMIN' | 'USER';
    export const RolEnum = {
        Admin: 'ADMIN' as RolEnum,
        User: 'USER' as RolEnum
    };
}


